// SPDX-License-Identifier: MIT
// GENERATED by scripts/dev/makeForkFixture.ts from Xai Testnet tx 0xf6ff7dd7118031e00f090a50cb2428cc46326d7f8038904d6c1187561abef8b8. Do not edit.
pragma solidity 0.8.28;

import {ExitClaim} from "../../interfaces/IExitMarket.sol";

library XaiExitFixture {
    uint256 internal constant FORK_BLOCK = 313884132;
    address internal constant PARENT_GATEWAY = 0xCcB451C4Df22addCFe1447c58bC6b2f264Bb1256;
    uint256 internal constant EXIT_NUM = 1;

    function claim() internal pure returns (ExitClaim memory c) {
        bytes32[] memory p = new bytes32[](7);
        p[0] = 0x5b58e649ad09cda349822d02cd27dcf8b073582cd557317ac0b21ff451894ebd;
        p[1] = 0x8118279882ef0aa73f935874aeb6462eb3ab12d35ef3b204643e7abf2f777ca1;
        p[2] = 0x9a1b2472ea94becad0d0423ea40bd3b831993614cf08750121dbd10571973d6e;
        p[3] = 0x6c91a7ba6b588e45a085e37eb23cb482b26ca234a1c0f6ab7465aa57a58700b5;
        p[4] = 0xc6200c7d2dcb9a2dc013b875588b879afc49e275a8636a9bfc16b9ae57967f50;
        p[5] = 0x361901ad78252469cd1fed5ea03bc3e68a4f3bef08f9749878fd5667a254d09b;
        p[6] = 0x2b1a5abffdad71fe37aeac3cdf0b4423c683023db55fd85de54011a7441840b5;
        c = ExitClaim({
            initialDestination: 0x4BDc704660B3710849e8C324469f863F8fC5cFAD,
            l1Token: 0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d,
            from: 0x4BDc704660B3710849e8C324469f863F8fC5cFAD,
            amount: 20000,
            l2Block: 5118911,
            l1Block: 6586353,
            l2Timestamp: 1724832600,
            index: 44,
            proof: p,
            sendRoot: 0xd8a1c3386ad861c9533e67e76d0f3e403adb04a819775a7ec0ca2404c462b583,
            nodeNum: 61783,
            blockHash: 0xc15b9e314d481b1b1fbdbb3d20cf1c5d8926ae42ed207e1b3a5126c4624253fa
        });
    }
}
