// SPDX-License-Identifier: MIT
// GENERATED by scripts/dev/makeForkFixture.ts from Xai Testnet tx 0xf6ff7dd7118031e00f090a50cb2428cc46326d7f8038904d6c1187561abef8b8. Do not edit.
pragma solidity 0.8.28;

import {ExitClaim} from "../../interfaces/IExitMarket.sol";

library XaiExitFixture {
    uint256 internal constant FORK_BLOCK = 314580748;
    address internal constant PARENT_GATEWAY = 0xCcB451C4Df22addCFe1447c58bC6b2f264Bb1256;
    uint256 internal constant EXIT_NUM = 1;

    function claim() internal pure returns (ExitClaim memory c) {
        bytes32[] memory p = new bytes32[](7);
        p[0] = 0x5b58e649ad09cda349822d02cd27dcf8b073582cd557317ac0b21ff451894ebd;
        p[1] = 0x8118279882ef0aa73f935874aeb6462eb3ab12d35ef3b204643e7abf2f777ca1;
        p[2] = 0x9a1b2472ea94becad0d0423ea40bd3b831993614cf08750121dbd10571973d6e;
        p[3] = 0x6c91a7ba6b588e45a085e37eb23cb482b26ca234a1c0f6ab7465aa57a58700b5;
        p[4] = 0xc6200c7d2dcb9a2dc013b875588b879afc49e275a8636a9bfc16b9ae57967f50;
        p[5] = 0x361901ad78252469cd1fed5ea03bc3e68a4f3bef08f9749878fd5667a254d09b;
        p[6] = 0x005dd25674edd4dba16b611e8b20266fe2e94d0676fb147c14bdb7b7b142faf4;
        c = ExitClaim({
            initialDestination: 0x4BDc704660B3710849e8C324469f863F8fC5cFAD,
            l1Token: 0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d,
            from: 0x4BDc704660B3710849e8C324469f863F8fC5cFAD,
            amount: 20000,
            l2Block: 5118911,
            l1Block: 6586353,
            l2Timestamp: 1724832600,
            index: 44,
            proof: p,
            sendRoot: 0x0fce088a5daee53e272d8cefa60414b5410bc96bd43bce505b92891f76b00cab,
            nodeNum: 61971,
            blockHash: 0x21fc8505109f4522495a2f12134387066cb6c63b3ca791734d7cbd77deca121e
        });
    }
}
