// SPDX-License-Identifier: MIT
// GENERATED by scripts/dev/makeForkFixture.ts from Xai Testnet tx 0x6cbac0526486a8b052b65361d74a6ac43a5b077186f14ee8fda8803136d1b28d. Do not edit.
pragma solidity 0.8.28;

import {ExitClaim} from "../../interfaces/IExitMarket.sol";

library XaiExitFixture {
    uint256 internal constant FORK_BLOCK = 314547360;
    address internal constant PARENT_GATEWAY = 0xCcB451C4Df22addCFe1447c58bC6b2f264Bb1256;
    uint256 internal constant EXIT_NUM = 15;

    function claim() internal pure returns (ExitClaim memory c) {
        bytes32[] memory p = new bytes32[](7);
        p[0] = 0xf27cbe48ade8775201173a94aab457b76536fa5bed9484dd68d6e704db31f212;
        p[1] = 0xab0e3071f5279e9b9e6a670de4f2135636d7790f8a3afa276bc8ef799eedd0b8;
        p[2] = 0xef9a2ac0344ea6c4c31c7cb20a9a0de3d06a09c2cb909a61c6047b8e4c5332e8;
        p[3] = 0x54a73563fef7d0e86c889cdb626bfe774c7db7e695d914ee6a5df965b556bc2a;
        p[4] = 0xdb5e374458d857c150230be6a508f86b3eb2e914a21950dabc3a75da27d0af74;
        p[5] = 0x0000000000000000000000000000000000000000000000000000000000000000;
        p[6] = 0x2355f193840f04fc94aed433f911e03a9935a907db640130efbaf69442f7ddd6;
        c = ExitClaim({
            initialDestination: 0xF194AE05D7BAccFB13A5A01e9D2adF50ea0c8A69,
            l1Token: 0xFFC95faa3d63Cde504a05B567C600B78C0b41892,
            from: 0xF194AE05D7BAccFB13A5A01e9D2adF50ea0c8A69,
            amount: 2000000,
            l2Block: 15219495,
            l1Block: 11819903,
            l2Timestamp: 1790834633,
            index: 87,
            proof: p,
            sendRoot: 0x0868eb79b9d96c65268447b7dcb63e7984d95cdfa44d727bbad26e41d35082a9,
            nodeNum: 61962,
            blockHash: 0xe04b0dcf754b2cc2f6126d53518eff1b5a572391ed361e92480b6686424a1060
        });
    }
}
