/**
 * Writes scripts/lib/abis.ts from the Hardhat artifacts, so every TypeScript consumer (web app, relayer, keeper,
 * scripts) uses the ABIs the contracts were compiled with instead of hand-written fragments.
 *   npx hardhat build && node scripts/dev/exportAbis.ts
 */
import { readFileSync, writeFileSync } from "node:fs";

const CONTRACTS = [
  ["exitMarketAbi", "ExitMarket.sol/ExitMarket"],
  ["exitVaultAbi", "ExitVault.sol/ExitVault"],
  ["exitIntentRouterAbi", "ExitIntentRouter.sol/ExitIntentRouter"],
  ["legacyRootVerifierAbi", "verifiers/LegacyRootVerifier.sol/LegacyRootVerifier"],
  ["boldRootVerifierAbi", "verifiers/BoldRootVerifier.sol/BoldRootVerifier"],
] as const;

const OUT = "scripts/lib/abis.ts";

const blocks = CONTRACTS.map(([name, path]) => {
  const artifact = JSON.parse(readFileSync(`artifacts/contracts/${path}.json`, "utf8")) as { abi: unknown[] };
  if (!Array.isArray(artifact.abi) || artifact.abi.length === 0) throw new Error(`Empty ABI in ${path}`);
  return `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
});

const header = `// GENERATED by scripts/dev/exportAbis.ts from the Hardhat artifacts. Do not edit by hand.\n\n`;
writeFileSync(OUT, `${header}${blocks.join("\n\n")}\n`);
console.log(`wrote ${OUT} (${CONTRACTS.length} contracts)`);
