/**
 * Generates contracts/test/fork/ArbOneExitFixture.sol: a REAL, pending Arbitrum One -> Ethereum token withdrawal,
 * proven against a REAL pending BOLD assertion on Ethereum mainnet by the shared library (scripts/lib/boldProof.ts),
 * so regenerating the fixture also checks the library end to end against mainnet.
 * Usage: node scripts/dev/makeArbOneFixture.ts   (ETH_RPC_URL optional; logs come from the Blockscout API)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { createPublicClient, decodeEventLog, encodeAbiParameters, http, parseAbi, parseAbiItem, toEventSelector, type Hex } from "viem";
import { arbitrum, mainnet } from "viem/chains";
import { ASSERTION_CREATED, buildBoldExitProof, toBoldAssertion, type BoldAssertion } from "../lib/boldProof.ts";

const ETH_RPC = process.env.ETH_RPC_URL ?? "https://ethereum-rpc.publicnode.com";
const eth = createPublicClient({ chain: mainnet, transport: http(ETH_RPC) });
const arb = createPublicClient({ chain: arbitrum, transport: http("https://arb1.arbitrum.io/rpc") });

const ROLLUP = "0x4DCeB440657f21083db8aDd07665f8ddBe1DCfc0"; // Arbitrum One BOLD rollup (bridge.rollup())
const OUTBOX = "0x0B9857ae2D4A3DBe74ffE1d7DF045bb7F96E4840";
const L2_ERC20_GATEWAY = "0x09e9222E96E7B4AE2a407B98d48e330053351EEe";
const L1_ERC20_GATEWAY = "0xa3A7B6F88361F48403514059F1F16C8E78d60EeC";
const WITHDRAWAL_INITIATED = parseAbiItem(
  "event WithdrawalInitiated(address l1Token, address indexed _from, address indexed _to, uint256 indexed _l2ToL1Id, uint256 _exitNum, uint256 _amount)",
);
const outboxAbi = parseAbi(["function isSpent(uint256) view returns (bool)"]);
/** ~6.4 days of Ethereum blocks (confirm period 45,818) plus margin, so the whole pending chain is in range. */
const WINDOW = 55_000n;
const CHUNK = 5_000n;
/** Arbitrum One blocks searched for a recent withdrawal (~1 day). */
const WITHDRAWAL_WINDOW = 400_000n;

// 1. Assertion history. Public full nodes refuse old logs ("archive"); the Blockscout log API serves them for free.
type RawLog = { data: Hex; topics: Hex[] };
const ethHead = await eth.getBlockNumber();
const assertions: BoldAssertion[] = [];
for (let from = ethHead - WINDOW; from <= ethHead; from += CHUNK) {
  const to = from + CHUNK - 1n > ethHead ? ethHead : from + CHUNK - 1n;
  const url = `https://eth.blockscout.com/api?module=logs&action=getLogs&address=${ROLLUP}&topic0=${toEventSelector(ASSERTION_CREATED)}&fromBlock=${from}&toBlock=${to}`;
  let json: { result?: RawLog[] } = {};
  for (let attempt = 0; attempt < 5 && !Array.isArray(json.result); attempt++) {
    if (attempt) await new Promise((r) => setTimeout(r, 2_000 * attempt));
    json = await (await fetch(url)).json();
  }
  for (const l of json.result ?? []) {
    const topics = l.topics.filter(Boolean) as [Hex, ...Hex[]];
    assertions.push(toBoldAssertion(decodeEventLog({ abi: [ASSERTION_CREATED], data: l.data, topics }).args));
  }
}
console.log(`Collected ${assertions.length} AssertionCreated events`);

// 2. A recent token withdrawal that is still unspent; the library picks the assertion to prove it against.
const arbHead = await arb.getBlockNumber();
const logs = await arb.getLogs({ address: L2_ERC20_GATEWAY, event: WITHDRAWAL_INITIATED, fromBlock: arbHead - WITHDRAWAL_WINDOW, toBlock: arbHead });
let built: Awaited<ReturnType<typeof buildBoldExitProof>> | undefined;
for (const l of [...logs].reverse()) {
  if (await eth.readContract({ address: OUTBOX, abi: outboxAbi, functionName: "isSpent", args: [l.args._l2ToL1Id!] })) continue;
  try {
    const candidate = await buildBoldExitProof({ parent: eth, child: arb, rollup: ROLLUP, childGateway: L2_ERC20_GATEWAY, withdrawalTx: l.transactionHash, assertions });
    if (candidate.covering.pending) {
      built = candidate;
      break;
    }
  } catch (err) {
    if ((err as Error).name !== "NotYetAssertedError") throw err; // newest withdrawals are not asserted yet
  }
}
if (!built) throw new Error("No pending, unspent, asserted withdrawal in the window");
const { withdrawal: w, covering } = built;
const { assertion, chain } = covering;
const after = assertion.afterState;
const [blockHash, sendRoot] = after.globalState.bytes32Vals;
console.log(`Exit #${w.exitNum} at position ${w.proof.index}: assertion ${assertion.assertionHash}, pending chain of ${chain.length}`);

const CHAIN_TUPLE = [{ type: "tuple[]", components: [
  { name: "parent", type: "bytes32" },
  { name: "afterState", type: "tuple", components: ASSERTION_CREATED.inputs[2].components![2].components },
  { name: "inboxAcc", type: "bytes32" },
] }] as const;
const chainHex = encodeAbiParameters(CHAIN_TUPLE as never, [chain.map((c) => ({ parent: c.parent, afterState: c.afterState, inboxAcc: c.inboxAcc }))] as never);
const p = w.proof;
const lines = p.merkleProof.map((h, i) => `        p[${i}] = ${h};`).join("\n");
const sol = `// SPDX-License-Identifier: MIT
// GENERATED by scripts/dev/makeArbOneFixture.ts (scripts/lib/boldProof.ts) from an Arbitrum One withdrawal
// (exit #${w.exitNum}) and pending BOLD assertion ${assertion.assertionHash}. Do not edit.
pragma solidity 0.8.28;

import {ExitClaim} from "../../interfaces/IExitMarket.sol";
import {BoldAssertionState, BoldGlobalState} from "../../interfaces/IBoldRollup.sol";

library ArbOneExitFixture {
    address internal constant ROLLUP = ${ROLLUP};
    address internal constant L1_GATEWAY = ${L1_ERC20_GATEWAY};
    uint256 internal constant EXIT_NUM = ${w.exitNum};
    bytes32 internal constant ASSERTION_HASH = ${assertion.assertionHash};
    bytes32 internal constant PARENT_ASSERTION_HASH = ${assertion.parent};
    bytes32 internal constant INBOX_ACC = ${assertion.inboxAcc};

    struct ChainLink {
        bytes32 parent;
        BoldAssertionState afterState;
        bytes32 inboxAcc;
    }

    /// @notice Every pending assertion from the latest confirmed one down to ASSERTION_HASH, oldest first.
    function chain() internal pure returns (ChainLink[] memory) {
        return abi.decode(hex"${chainHex.slice(2)}", (ChainLink[]));
    }

    function afterState() internal pure returns (BoldAssertionState memory s) {
        s.globalState = BoldGlobalState({
            bytes32Vals: [bytes32(${blockHash}), bytes32(${sendRoot})],
            u64Vals: [uint64(${after.globalState.u64Vals[0]}), uint64(${after.globalState.u64Vals[1]})]
        });
        s.machineStatus = ${after.machineStatus};
        s.endHistoryRoot = ${after.endHistoryRoot};
    }

    function claim() internal pure returns (ExitClaim memory c) {
        bytes32[] memory p = new bytes32[](${p.merkleProof.length});
${lines}
        c = ExitClaim({
            initialDestination: ${w.initialDestination},
            l1Token: ${p.l1Token},
            from: ${p.from},
            amount: ${p.amount},
            l2Block: ${p.l2Block},
            l1Block: ${p.l1Block},
            l2Timestamp: ${p.l2Timestamp},
            index: ${p.index},
            proof: p,
            sendRoot: ${p.sendRoot},
            nodeNum: 0,
            blockHash: ${p.blockHash}
        });
    }
}
`;
mkdirSync("contracts/test/fork", { recursive: true });
writeFileSync("contracts/test/fork/ArbOneExitFixture.sol", sol);
console.log("Wrote contracts/test/fork/ArbOneExitFixture.sol");
