/**
 * Generates contracts/test/fork/XaiExitFixture.sol: a real, UNSPENT Xai Testnet withdrawal with its proof
 * against the newest rollup node, pinned to the current Arbitrum Sepolia block for a fork test.
 * Usage: node scripts/dev/makeForkFixture.ts <withdrawal-tx-hash>
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { createPublicClient, http, type Hex } from "viem";
import { arbitrumSepolia } from "viem/chains";
import { buildExitProof } from "../lib/exitProof.ts";
import { XAI_TESTNET } from "../lib/networks.ts";

const tx = process.argv[2] as Hex | undefined;
if (!tx) throw new Error("Usage: node scripts/dev/makeForkFixture.ts <withdrawal-tx-hash>");

const parent = createPublicClient({ chain: arbitrumSepolia, transport: http("https://sepolia-rollup.arbitrum.io/rpc") });
const child = createPublicClient({ transport: http(XAI_TESTNET.rpcUrl) });

const forkBlock = await parent.getBlockNumber();
const w = await buildExitProof({
  parent,
  child,
  rollup: XAI_TESTNET.ethBridge.rollup,
  childGateway: XAI_TESTNET.tokenBridge.childErc20Gateway,
  withdrawalTx: tx,
});
const p = w.proof;
const proofLines = p.merkleProof.map((h, i) => `        p[${i}] = ${h};`).join("\n");

const sol = `// SPDX-License-Identifier: MIT
// GENERATED by scripts/dev/makeForkFixture.ts from Xai Testnet tx ${tx}. Do not edit.
pragma solidity 0.8.28;

import {ExitClaim} from "../../interfaces/IExitMarket.sol";

library XaiExitFixture {
    uint256 internal constant FORK_BLOCK = ${forkBlock};
    address internal constant PARENT_GATEWAY = ${XAI_TESTNET.tokenBridge.parentErc20Gateway};
    uint256 internal constant EXIT_NUM = ${w.exitNum};

    function claim() internal pure returns (ExitClaim memory c) {
        bytes32[] memory p = new bytes32[](${p.merkleProof.length});
${proofLines}
        c = ExitClaim({
            initialDestination: ${w.initialDestination},
            l1Token: ${p.l1Token},
            from: ${p.from},
            amount: ${p.amount},
            l2Block: ${p.l2Block},
            l1Block: ${p.l1Block},
            l2Timestamp: ${p.l2Timestamp},
            index: ${p.index},
            proof: p,
            sendRoot: ${p.sendRoot},
            nodeNum: ${p.nodeNum},
            blockHash: ${p.blockHash}
        });
    }
}
`;

mkdirSync("contracts/test/fork", { recursive: true });
writeFileSync("contracts/test/fork/XaiExitFixture.sol", sol);
console.log(`Wrote fixture: exit #${w.exitNum}, index ${p.index}, node ${p.nodeNum}, fork block ${forkBlock}`);
